taikang-claims:
   transactional:
     enabled: true
#注入攻击处理
   filter:
     injection-attack-interceptor:
        enabled: false
spring:
  # 多环境配置文件
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    generator:
      write_numbers_as_strings: true
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  session:
    store-type: redis
    redis:
      flush-mode: immediate

server:
  compression:
    enabled: true
    mime-types: application/json
  port: 15002
  servlet:
    context-path: /dynamic
  aop:
    proxy-target-class: true
    auto: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package:  com.xiong.service.*.entity
  type-enums-package: com.xiong.service.*.entity.enums
  global-config:
    db-config:
      # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      # 驼峰下划线转换
      db-column-underline: true
      # 刷新mapper 调试神器
      refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
#    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


swagger:
  enabled: true