# 日志
logging:
  config: classpath:log4j2-show.xml

spring:
  autoconfigure:
    # 排除掉druid的原生配置
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      # 以下是全局默认值，可以全局更改(所有数据源, 可以针对数据源做单独设置)
      druid:
        mysql:
          usePingMethod: false
        # 监控统计拦截的filters
        filters: stat
        # 配置初始化大小/最小/最大
        initial-size: 1
        min-idle: 1
        max-active: 20
        # 获取连接等待超时时间
        max-wait: 60000
        # 间隔多久进行一次检测，检测需要关闭的空闲连接
        time-between-eviction-runs-millis: 60000
        # 一个连接在池中最小生存的时间
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 'x'
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: 20
        stat:
          merge-sql: true
          log-slow-sql: true
          slow-sql-millis: 2000
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: his
      # 设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源
      strict: false
      datasource:
        his:
          url: jdbc:mysql://192.168.29.188:3306/his?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: zhyx
          password: zhyx
        log:
          url: jdbc:mysql://192.168.29.188:3306/log?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: zhyx
          password: zhyx
        dict:
          url: jdbc:mysql://192.168.29.188:3306/dict?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: zhyx
          password: zhyx

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
